fos_rest:
    format_listener:
        rules:
            - { path: ^/ }
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
            - { path: ^/admin, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
            - { path: ^/preview }

